#!/usr/bin/env python3
"""
compute_power.py
Compute power and energy efficiency metrics for MiniRocketHLS paper.

Power source: xbutil examine --report electrical (measured on Alveo U280)
CPU power: estimated from server TDP (common practice in FPGA papers)

Outputs:
  results/tables/power_table.tex — LaTeX power/energy efficiency table
  stdout — summary for paper writing
"""

import os
import sys
import csv

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
RESULTS_DIR = os.path.join(PROJECT_ROOT, "results")
TABLES_DIR = os.path.join(RESULTS_DIR, "tables")

# ── Measured Power Data ──
# FPGA: Alveo U280, measured via `xbutil examine --report electrical`
# 12V Aux: 12.2V × 0.79A = 9.6W
# 12V PCIe: 12.2V × 1.21A = 14.8W
# Total: 24.4W (includes board idle power, HBM, CMAC if present)
FPGA_POWER_W = 24.4

# CPU: Server-class CPU (Xeon or similar)
# TDP-based estimate: common practice in FPGA papers (InceptionTime, OS-CNN, etc.)
# Conservative estimate — actual compute power is lower than full TDP
CPU_TDP_W = 100.0


def load_results():
    """Load throughput data from results_master.csv"""
    csv_path = os.path.join(RESULTS_DIR, "results_master.csv")
    results = {}
    with open(csv_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            key = (row['Algorithm'], row['Dataset'], row['Platform'], row['Config'])
            tp = row['Throughput_InfPerSec']
            if not tp:
                continue
            results[key] = {
                'throughput': float(tp),
                'accuracy': float(row['Accuracy_Pct']) if row['Accuracy_Pct'] else 0,
            }
    return results


def compute_power_metrics():
    results = load_results()

    # Define configurations to compare: (algo, label, platform, config, power)
    configs = [
        ("MiniRocket", "CPU C++ (-O3)", "CPU (C++ -O3)", "per-sample", CPU_TDP_W),
        ("MiniRocket", "FPGA 1-CU", "FPGA U280 (fused 1CU)", "300MHz", FPGA_POWER_W),
        ("MiniRocket", "FPGA 2-CU", "FPGA U280 (fused 2CU)", "300MHz", FPGA_POWER_W),
        ("MiniRocket", "FPGA 3-CU", "FPGA U280 (fused 3CU)", "269MHz", FPGA_POWER_W),
    ]

    datasets = ['InsectSound', 'MosquitoSound', 'FruitFlies']

    print("=" * 80)
    print("POWER AND ENERGY EFFICIENCY ANALYSIS")
    print("=" * 80)
    print(f"\nFPGA Power: {FPGA_POWER_W}W (measured, xbutil electrical)")
    print(f"CPU Power:  {CPU_TDP_W}W (TDP estimate)")
    print()

    # Collect data for table
    table_rows = []

    for dataset in datasets:
        print(f"\n--- {dataset} ---")
        cpu_throughput = None
        cpu_eff = None

        for algo, label, platform, config, power in configs:
            key = (algo, dataset, platform, config)
            if key not in results:
                print(f"  {label}: NO DATA")
                continue

            tp = results[key]['throughput']
            eff = tp / power  # inf/J = inf/s / W
            energy_mj = 1000.0 / tp * power  # mJ per inference

            if 'CPU' in platform:
                cpu_throughput = tp
                cpu_eff = tp / power

            speedup = tp / cpu_throughput if cpu_throughput else 0
            eff_ratio = eff / cpu_eff if cpu_eff else 0

            print(f"  {label:15s}: {tp:8.1f} inf/s | {power:5.1f}W | "
                  f"{eff:7.1f} inf/J | {energy_mj:7.2f} mJ/inf | "
                  f"{eff_ratio:5.1f}x energy eff")

            table_rows.append({
                'dataset': dataset,
                'label': label,
                'throughput': tp,
                'power': power,
                'efficiency': eff,
                'energy_mj': energy_mj,
                'speedup': speedup,
                'eff_ratio': eff_ratio,
            })

    # Generate LaTeX table
    os.makedirs(TABLES_DIR, exist_ok=True)
    tex_path = os.path.join(TABLES_DIR, "power_table.tex")

    with open(tex_path, 'w') as f:
        f.write("% Auto-generated by compute_power.py\n")
        f.write("% FPGA: 24.4W measured (xbutil electrical), CPU: 100W TDP estimate\n")
        f.write("\\begin{table}[t]\n")
        f.write("\\centering\n")
        f.write("\\caption{Energy Efficiency: MiniRocket Fused Kernel on Alveo U280}\n")
        f.write("\\label{tab:power}\n")
        f.write("\\small\n")
        f.write("\\begin{tabular}{llrrrrr}\n")
        f.write("\\toprule\n")
        f.write("Dataset & Platform & Throughput & Power & Efficiency & Energy & Eff. \\\\\n")
        f.write(" & & (inf/s) & (W) & (inf/J) & (mJ/inf) & Ratio \\\\\n")
        f.write("\\midrule\n")

        prev_dataset = None
        for row in table_rows:
            ds = row['dataset']
            if prev_dataset and ds != prev_dataset:
                f.write("\\midrule\n")
            prev_dataset = ds

            ds_display = ds if (prev_dataset != ds or table_rows.index(row) == 0 or
                                table_rows[table_rows.index(row)-1]['dataset'] != ds) else ""
            # Only show dataset name on first row of group
            if table_rows.index(row) > 0 and table_rows[table_rows.index(row)-1]['dataset'] == ds:
                ds_display = ""

            eff_str = f"{row['eff_ratio']:.0f}$\\times$" if row['eff_ratio'] > 1 else "1$\\times$"

            f.write(f"{ds_display} & {row['label']} & "
                    f"{row['throughput']:,.0f} & {row['power']:.0f} & "
                    f"{row['efficiency']:.1f} & {row['energy_mj']:.2f} & "
                    f"{eff_str} \\\\\n")

        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
        f.write("\\end{table}\n")

    print(f"\n\nLaTeX table written to: {tex_path}")

    # Print summary for paper narrative
    print("\n" + "=" * 80)
    print("KEY CLAIMS FOR PAPER:")
    print("=" * 80)

    # Find best efficiency ratios
    fpga_rows = [r for r in table_rows if 'FPGA' in r['label']]
    if fpga_rows:
        best_eff = max(fpga_rows, key=lambda r: r['eff_ratio'])
        min_energy = min(fpga_rows, key=lambda r: r['energy_mj'])
        print(f"  Best energy efficiency ratio: {best_eff['eff_ratio']:.0f}x "
              f"({best_eff['label']}, {best_eff['dataset']})")
        print(f"  Lowest energy per inference: {min_energy['energy_mj']:.2f} mJ/inf "
              f"({min_energy['label']}, {min_energy['dataset']})")

        # Range across datasets
        three_cu = [r for r in fpga_rows if '3-CU' in r['label']]
        if three_cu:
            min_r = min(three_cu, key=lambda r: r['eff_ratio'])
            max_r = max(three_cu, key=lambda r: r['eff_ratio'])
            print(f"  3-CU efficiency ratio range: {min_r['eff_ratio']:.0f}x - {max_r['eff_ratio']:.0f}x")
            print(f"  3-CU energy range: {min(r['energy_mj'] for r in three_cu):.2f} - "
                  f"{max(r['energy_mj'] for r in three_cu):.2f} mJ/inf")


if __name__ == '__main__':
    compute_power_metrics()
